
Scheme = 'Primer3DSFail'
Scheme_UITests = 'Primer3DSFail'
Screenshots_Output = 'build/screenshots' 

AppIdentifier = 'com.pace.Primer3DSFail'

skip_docs

default_platform(:ios)

platform :ios do
  desc 'Run UITests'
  lane :ui_test do
    capture_ios_screenshots(
      app_identifier: AppIdentifier,
      configuration: 'Debug',
      output_directory: Screenshots_Output,
      scheme: Scheme_UITests,
      languages: [ "en-US" ],
      devices: [ "iPhone 14 Pro Max" ]
    )
  end
end