name: UI Test

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app

      - name: Install Gem Dependencies
        run: |
          bundle config path vendor/bundle
          bundle install
          
      - name: Run UITests
        run: bundle exec fastlane ui_test

      - name: Upload screenshots
        uses: actions/upload-artifact@v1
        with:
          name: Screenshots
          path: build/screenshots
