name: Xcode build iOS 16

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: "Cache Derived Data"
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData/Primer3DSFail-*/Build
            ~/Library/Developer/Xcode/DerivedData/Primer3DSFail-*/SourcePackages
          key: ${{ runner.os }}-derivedData-cache-${{ hashFiles('Primer3DSFail.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-derivedData-cache-
      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
            
      - name: Avoid inode changes for DerivedData
        run: defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

        shell: bash


      - name: Install Dependencies
        run: |
          pod install
        shell: bash
      - name: Xcode iOS build
        run: |
          xcodebuild -workspace Primer3DSFail.xcworkspace -scheme Primer3DSFail -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.1' | xcpretty
    
      - name: UI TEST
        run: |
          xcodebuild -workspace Primer3DSFail.xcworkspace -scheme "Primer3DSFail" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.1' test  | xcpretty