name: UI Test

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_14.1.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version
        shell: bash

      - name: Install Dependencies
        run: |
          pod install
        shell: bash

      # - name: Xcode iOS build
      #   run: |
      #     xcodebuild -workspace Primer3DSFail.xcworkspace -scheme Primer3DSFail -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.1' | xcpretty
    
      - name: UI TEST
        run: |
          set -o pipefail && xcodebuild -workspace Primer3DSFail.xcworkspace -scheme "Primer3DSFail" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.1' test  | xcpretty